#!/usr/bin/ruby
require "openai"
require "readline"

START_PROMPT=<<-EOF
You will be executing commands on an ArchLinux system. I will give you a task, and you will execute it by sending me the exact commands needed to perform the task. You are the root user.

example: reboot the system
reboot

example: restart the network manager
systemctl restart NetworkManager

EOF

$client = OpenAI::Client.new(access_token: ENV["ACCESS_TOKEN"])
# Don't actually execute the command
DRY=if ENV["DRY"] then ENV["DRY"] == "1" else true end
SHOWPROMPT=if ENV["SHOWPROMPT"] then ENV["SHOWPROMPT"] == "1" else false end

abort "You should set the ACCESS_TOKEN environment variable" if !ENV["ACCESS_TOKEN"]

$prompt = START_PROMPT

def ask line
    $prompt = $prompt + line + "..."
    res = $client.completions(
        parameters: {
            model: "text-davinci-003",
            prompt: $prompt,
            stop: "..."
        }
    )

    out = res["choices"].map { |c| c["text"] }[0]
    $prompt += out + "\n\n"
    return out.strip
end

while line = Readline.readline("gpt> ", true)
    cmd = ask line

    puts $prompt if SHOWPROMPT
    
    puts "\e[1;34m>>\e[0m #{cmd.inspect}"
    if !DRY
        print `#{cmd}`
    else
        puts "not executing while in DRY mode"
    end
end
